language: swift

osx_image: xcode10.2
env:
  matrix:
    - TEST_SDK=iphonesimulator12.2 OS=12.2 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.2 OS=12.2 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild -version
  - set -o pipefail && xcodebuild -showsdks 

  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project TestFramework.xcodeproj -scheme TestFramework -sdk $TEST_SDK -destination 'platform=iOS Simulator,OS=12.2,name=iPhone XR' ONLY_ACTIVE_ARCH=YES
