language: objective-c

osx_image: xcode10.1
env:
  matrix:
    - TEST_SDK=iphonesimulator12.0 OS=12.0 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.0 OS=12.0 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project TestFramework.xcodeproj -scheme TestFramework -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
